# Listas y como recorrerlas:

Comenzamos estudiando los arrays y las formas de recorrerlos

In [76]:
# array
arr1 = ["algebra 1", "calculo 1", "matematica discreta"] 
print("El tipo de objeto es: ",type(arr1))


El tipo de objeto es:  <class 'list'>


Los arrays en python son objetos tipo "lista", que tienen sus funciones (append,insert, etc).

Para recorrerlo y trabajar con el:

In [77]:
for i in arr1: # i es un ELEMENTO del array, a diferencia de otros lenguajes
  print(i)



algebra 1
calculo 1
matematica discreta


In [78]:
# tambien se puede usar una estructura mas tradicional:

for i in range(len(arr1)):
  print(f"valor de i: {i}, elemento: {arr1[i]}")



valor de i: 0, elemento: algebra 1
valor de i: 1, elemento: calculo 1
valor de i: 2, elemento: matematica discreta


In [79]:
# otra forma:

for i, materia in enumerate(arr1): # una forma de combinar ambas formas de recorrer
  print(f"valor de i: {i}, materia: {materia}")

valor de i: 0, materia: algebra 1
valor de i: 1, materia: calculo 1
valor de i: 2, materia: matematica discreta


Existen diversas formas de agregar elementos a arrays


In [90]:
# agregamos la mejor matematica de ela catedra:

arr1.append("probabilidad y estadística")
print("Array original, pero con la mejor matemática agregada al final:",arr1)

# si queremos obtener los elementos del 1 al 2:

print("Elementos del 1 al 3: ",arr1[1:3]) # no incluye al 3. Numericamente es comodo

# si queremos el ultimo elemento:
print("Ultimo elemento:",arr1[-1])

# si queremos los elementos del 2 al ultimo:
print("elementos del 3 en adelante:",arr1[2:-1])

Array original, pero con la mejor matemática agregada al final: ['algebra 1', 'calculo 1', 'matematica discreta', 'probabilidad y estadística', 'probabilidad y estadística', 'probabilidad y estadística']
Elementos del 1 al 3:  ['calculo 1', 'matematica discreta']
Ultimo elemento: probabilidad y estadística
elementos del 3 en adelante: ['matematica discreta', 'probabilidad y estadística', 'probabilidad y estadística']


Para trabajar con arrays numéricos, recomendamos utilizar los objetos "nump array" que vienen con sus propias funciones mas orientadas al algebra

In [81]:
import numpy as np
arr2 = [1, 2, 3, 4, 5]
arr2 = np.array(arr2) # lo convertimos a numpy array.

# arr2 mantiene todas las propiedades de una lista normal, pero tenemos mas funciones.


print("El tipo es:",type(arr2))


El tipo es: <class 'numpy.ndarray'>


In [82]:
# arr2 es compatible con operaciones matematicas

print("Elementos de arr2 al cuadrado: ",np.power(arr2, 2))

# imprimir solo los numeros pares:

print("Elementos pares de arr2:")
for i in arr2:
  if i%2 == 0:
    print(i)





Elementos de arr2 al cuadrado:  [ 1  4  9 16 25]
Elementos pares de arr2:
2
4


In [94]:
# otra forma de hacerlo:
# para python, 0 = FALSE y cualquier cosa distinto de 0 = TRUE, podemos hacer uso de eso
print("Elementos pares de arr2")
for i in arr2:
  if not i%2: 
    print(i)

# si queremos los impares:
print("Elementos impares de arr2")
for i in arr2:
  if i%2: # si i%2 es 0, entonces la condicion es FALSE y no entra. Si i%2 es 1 (impar) entonces es TRUE y entra
    print(i)


Elementos pares de arr2
2
4
Elementos impares de arr2
1
3
5


# Ejemplo: ejercicio 3 del parcial de 2022
$$A = 
\begin{pmatrix}
\frac{1}{\sqrt{2}} & \frac{-1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\end{pmatrix}$$

Problema:
* Probar que $A^{8} = I$
* Hallar valores y vectores propios

In [84]:
# Parte 1


a = np.matrix([[1, -1],[1,1]]) # defino el objeto matriz
const = np.divide(1,np.sqrt(2)) # defino el 1/sqrt(2) (puedo hacer 1/np.sqrt(2) tambien)
a = np.dot(a, const) # multiplico la matriz por 1/sqrt(2). Uso la funcion np.dot (puedo hacer a*const tambien)


print(f"La matriz es: \n {a}")
print("\n")
print(f"La matriz elevada a la 8 es: \n {np.linalg.matrix_power(a, 8)}") # elevo la matriz a la 8


La matriz es: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


La matriz elevada a la 8 es: 
 [[ 1.00000000e+00  2.39116835e-33]
 [-2.39116835e-33  1.00000000e+00]]


Por errores de punto flotante, la potencia a la 8 dio con residuos, lo corregimos haciendo una funcion que redondee elemento a elemento:


In [85]:
def cleanMatrix(mat, decimals = 2):
  # Descripcion: funcion que "limpia" una matriz de errores de punto flotante

  # Inputs: 
  # mat, objeto np.matrix 
  # decimals: (int) cantidad de decimales a redondear, por defecto en 2

  # Outputs:
  # mat redondeada, objeto np matrix
  return np.matrix.round(mat, decimals)

  

In [86]:
print(f"La matriz elevada a la 8 (limpia) es: \n {cleanMatrix(np.linalg.matrix_power(a, 8))}") # elevo la matriz a la 8

La matriz elevada a la 8 (limpia) es: 
 [[ 1.  0.]
 [-0.  1.]]


In [87]:
# Parte 2

data = np.linalg.eig(a) 
# buscar en documentacion la funcion "numpy.linalg.eig()" para entender que estructura retorna:

valores_propios = data[0] 
vectores_propios = data[1]

print(f"los valores propios son: \n {valores_propios[0]} \n y: \n {valores_propios[1]}") # recordar que j es la unidad imaginaria
print(f"los vectores propios son:  \n {vectores_propios[0]}\n \n y \n \n {vectores_propios[1]} \n")




los valores propios son: 
 (0.7071067811865475+0.7071067811865475j) 
 y: 
 (0.7071067811865475-0.7071067811865475j)
los vectores propios son:  
 [[0.70710678+0.j 0.70710678-0.j]]
 
 y 
 
 [[0.-0.70710678j 0.+0.70710678j]] 



## Ejemplo: programacion lineal (ejercicio 7.6):
 Se dispone de un campo de 480 hectáreas, en el que se puede plantar maíz o trigo, en
superficies a definir. El maíz genera ganancias de $30/ha$, y el trigo $40/ha$. Por otra
parte, plantar una hectárea de maíz requiere 10 horas de tractor, una de trigo $20$ horas
de tractor, y el tractor está disponible un máximo de $8000$ horas. Hallar las superficies
óptimas a sembrar de cada grano para maximizar la ganancia.

## Solucion:

Consideramos:

* $x_1$ = "cantidad de hectáreas de maiz"
* $x_2$ = "cantidad de hectáreas de trigo"

El problema queda de la forma:


 $$ \text{max } 30x_1 + 40x_2$$

$$\text{Sujeto a:} \\  x_1+x_2 \leq 480 ; \\
10x_1+20x_2 \leq 8000; \\
x_1 \geq 0; \\
x_2 \geq 0;$$

Usamos la libreria CVXPY para resolver problemas de optimizacion

In [96]:

import cvxpy as cp

print("Solvers instalados: ",cp.installed_solvers())


--------------------------------------------
Solvers instalados:  ['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCIPY', 'SCS']
--------------------------------------------


Obligaremos a CVXPY a usar el solver 'GLPK' que usa SIMPLEX (ver documentacion)

Formulando el problema:

In [99]:
x = cp.Variable(2, nonneg = True) # Definimos vector (x, y) y ya lo seteamos en no negativo.


#-------------FORMULACION DE FUNCION OBJETIVO-------------#
c = np.array([30.0, 40.0]) # vector c
objective = cp.Maximize(c.T @ x) # para cvxpy el producto matricial es con @. (c.T es la traspuesta de c).

#---------------------------------------------------------#


#-------------FORMULACION DE CONSTRAINTS------------------#
A = np.matrix([[1,1] , [10, 20]]) # matriz de desigualdades
b = np.array([480, 8000]) # vector b
constraints = [A @ x <= b]
#---------------------------------------------------------#


#---------------MODELADO y SOLUCION-----------------------#

# Creacion del OBJETO problema
prob = cp.Problem(objective, constraints)




# Solucion del problema
result = prob.solve(solver = 'GLPK') # valor de la funcion objetivo, el vector solucion esta en "x.value". Le pasamos como parametro "GLPK" para que use ese solver.

print(f' Cantidad de hectareas de maiz:  {x.value[0]} \n Cantidad de hectareas de trigo: {x.value[1]} \n Presupuesto: ${result}')



 Cantidad de hectareas de maiz:  160.0 
 Cantidad de hectareas de trigo: 320.0 
 Presupuesto: $17600.0
